### PR TITLE
Add RLWE to OpenSSL_1_0_2-stable

### PR DESCRIPTION
**Pull request by mofojed**
Cherry-picked the RLWE change onto the latest OpenSSL_1_0_2-stable branch.

### CODE REVIEW

**Comment by dstebila** [comment]
Thanks for this.  I am in the process of restructuring the RLWE code to make it easier to integrate it and other post-quantum crypto primitives into OpenSSL.  Should have something ready to release in the next month or so.  At that point it should also be easier to keep it up to date with OpenSSL development.

**Comment by mofojed** [comment]
Cool, anything you need help with? I'm an enthusiast interested in learning
more about post-quantum crypto. Testing, code review, research, let me know
if there's anything I might be able to contribute (without getting in your
way, of course).

Cheers,
Mike

**Comment by dstebila** [comment]
Yeah, there will definitely be some things you can help with, thanks!  Drop me a line by email (douglas@stebila.ca) and we can coordinate from there.  Initial development is taking place off of Github, but we are planning to post to Github by the end of the summer.

Douglas

**Comment by dstebila** [comment]
I've been working on a new project that will incorporate a variety of post-quantum key exchange protocols, including this ring-LWE protocol, and integrate them into OpenSSL. The new project has what I hope is a better & simpler integration into OpenSSL.  And the integration is in OpenSSL 1.0.2. I'm not planning on maintaining this repository any more, instead directing my efforts to the new project. It's at [https://github.com/open-quantum-safe/openssl](https://github.com/open-quantum-safe/openssl).

**Pull request closed without merging**
